import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"

export function FaqSection() {
  const faqs = [
    {
      question: "How does the AI name generator work?",
      answer:
        "Our AI name generator uses advanced machine learning algorithms to create unique, contextually appropriate names and usernames. It analyzes patterns from successful usernames across different platforms and generates new options based on your specified parameters like platform type, theme, and purpose.",
    },
    {
      question: "Are the generated names unique?",
      answer:
        "While our AI strives to create unique names, we cannot guarantee that a generated name isn't already in use on your target platform. We recommend checking availability on the specific platform before committing to a name.",
    },
    {
      question: "Can I use the generated names commercially?",
      answer:
        "Yes! All names generated by our tool are free to use for any purpose, including commercial use. There are no copyright restrictions on the generated names.",
    },
    {
      question: "How many names can I generate?",
      answer:
        "You can generate up to 10 names at once, and there's no limit to how many times you can use the generator. Feel free to keep generating until you find the perfect name!",
    },
    {
      question: "Can I save my favorite generated names?",
      answer:
        "Yes, you can save your favorite names by clicking the bookmark icon. These will be stored locally in your browser for future reference.",
    },
    {
      question: "Is this service free to use?",
      answer: "Yes, our AI name generator is completely free to use with no hidden fees or subscription requirements.",
    },
  ]

  return (
    <section id="faq" className="py-24">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-2xl lg:text-center">
          <h2 className="text-base font-semibold leading-7 text-primary">FAQ</h2>
          <p className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Frequently asked questions</p>
          <p className="mt-6 text-lg leading-8 text-muted-foreground">
            Get answers to common questions about our AI name generator.
          </p>
        </div>
        <div className="mx-auto mt-16 max-w-2xl">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left">{faq.question}</AccordionTrigger>
                <AccordionContent>{faq.answer}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  )
}

